name: Publish Package

on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install toml --user

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
  
      - name: Update version in pyproject.toml
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          python <<EOF
          import toml
          import os

          version = os.getenv("VERSION")

          with open("pyproject.toml", "r") as f:
              data = toml.load(f)

          data["project"]["version"] = version

          with open("pyproject.toml", "w") as f:
              toml.dump(data, f)
          EOF
          
      - name: Install pypa/build
        run: python3 -m pip install build --user

      - name: Build binary wheel and source tarball
        run: python3 -m build

      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download all dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          verbose: true

  release:
    name: Create GitHub Release
    needs:
      - publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >
          gh release create
          "$GITHUB_REF_NAME"
          --repo "$GITHUB_REPOSITORY"
          --generate-notes
          --draft
